"""Failure Recovery and ReAct Analysis System

Implements failure-triggered reasoning:
1. Track consecutive failures per task
2. After 2 failures, trigger ReAct analysis
3. ReAct analyzes why, system environment, capabilities
4. Create solution plan and execute

[PHASE8] 规划推理 - FailureRecovery + ReActAnalysis
"""

import os
import time
from typing import Optional, Dict, Any, List, Tuple
from dataclasses import dataclass, field
from enum import Enum

# Debug print helper
def _debug(msg: str):
    print(f"[PHASE8] [Recovery] {msg}")


class FailurePhase(Enum):
    """Phase of failure in the recovery process"""
    INITIAL = "initial"           # First failure
    REACT_TRIGGERED = "react"     # ReAct reasoning triggered
    PLANNING = "planning"         # Creating solution plan
    EXECUTING_PLAN = "executing"  # Executing the plan
    RECOVERED = "recovered"       # Successfully recovered
    GIVE_UP = "give_up"          # Giving up after max attempts


@dataclass
class FailureContext:
    """Context about the failure"""
    task: str                     # Original user task
    failure_count: int           # Number of consecutive failures
    last_tool: str               # Last tool that failed
    last_result: str             # Last tool result
    error_message: str           # Error message if any
    judge_advice: str            # Advice from judge system
    attempts: List[Dict]         # History of attempts


@dataclass
class AnalysisResult:
    """Result from ReAct analysis"""
    diagnosis: str                # Why it failed (full flow analysis)
    environment: Dict[str, Any]   # Current environment info
    capabilities: List[str]      # Available tools/capabilities
    solution_plan: List[str]      # Step-by-step plan to solve
    confidence: float            # Confidence in the plan (0-1)
    reasoning_trace: List[Dict]  # Full reasoning steps
    root_causes: List[str]       # Root causes of failure
    gap_analysis: str            # Gap between user needs and output


class FailureRecovery:
    """Tracks failures and triggers ReAct analysis after threshold"""

    def __init__(self, max_failures_before_react: int = 2):
        self.max_failures_before_react = max_failures_before_react
        self._failure_context: Optional[FailureContext] = None
        self._current_phase = FailurePhase.INITIAL
        self._react_plan: Optional[List[str]] = None
        self._attempt_history: List[Dict] = []

    def record_failure(
        self,
        task: str,
        tool_name: str,
        tool_result: str,
        error: str = "",
        judge_advice: str = ""
    ) -> Tuple[bool, FailurePhase]:
        """Record a failure and check if ReAct should be triggered.

        Returns:
            (should_trigger_react, current_phase)
        """
        _debug(f"[record_failure] called: task={task[:50]}, tool={tool_name}, current_history_len={len(self._attempt_history)}")
        self._attempt_history.append({
            "tool": tool_name,
            "result": tool_result[:200] if tool_result else "",
            "error": error,
            "judge_advice": judge_advice,
            "timestamp": time.time()
        })

        self._failure_context = FailureContext(
            task=task,
            failure_count=len(self._attempt_history),
            last_tool=tool_name,
            last_result=tool_result,
            error_message=error,
            judge_advice=judge_advice,
            attempts=self._attempt_history.copy()
        )

        if len(self._attempt_history) >= self.max_failures_before_react:
            self._current_phase = FailurePhase.REACT_TRIGGERED
            _debug(f"[record_failure] threshold reached! history_len={len(self._attempt_history)}, max={self.max_failures_before_react}, should_react=True")
            return (True, FailurePhase.REACT_TRIGGERED)

        _debug(f"[record_failure] below threshold: history_len={len(self._attempt_history)}, max={self.max_failures_before_react}, should_react=False")
        self._current_phase = FailurePhase.INITIAL
        return (False, FailurePhase.INITIAL)

    def get_failure_context(self) -> Optional[FailureContext]:
        """Get the current failure context"""
        return self._failure_context

    def set_react_plan(self, plan: List[str]) -> None:
        """Set the plan generated by ReAct"""
        self._react_plan = plan
        self._current_phase = FailurePhase.PLANNING

    def get_next_action(self) -> Optional[str]:
        """Get the next action from the ReAct plan"""
        if self._react_plan and self._current_phase == FailurePhase.PLANNING:
            return self._react_plan[0] if self._react_plan else None
        return None

    def complete_action(self) -> bool:
        """Mark current action as complete and move to next"""
        if self._react_plan and self._react_plan:
            self._react_plan = self._react_plan[1:]
            if not self._react_plan:
                self._current_phase = FailurePhase.EXECUTING_PLAN
            return True
        return False

    def mark_recovered(self) -> None:
        """Mark the task as recovered"""
        self._current_phase = FailurePhase.RECOVERED
        self._attempt_history.clear()

    def mark_give_up(self) -> None:
        """Mark as giving up"""
        self._current_phase = FailurePhase.GIVE_UP

    def reset(self) -> None:
        """Reset the recovery state"""
        self._failure_context = None
        self._current_phase = FailurePhase.INITIAL
        self._react_plan = None
        self._attempt_history.clear()

    @property
    def current_phase(self) -> FailurePhase:
        return self._current_phase


class ReActAnalyzer:
    """ReAct-based failure analyzer and planner

    Uses ReAct reasoning to:
    1. Diagnose why previous attempts failed
    2. Analyze current environment and capabilities
    3. Create a concrete solution plan
    """

    # Analysis prompt template
    ANALYSIS_PROMPT = """你是一个失败分析与规划。你的任务是从用户需求出发，并制定解决方案。

## 用户需求（根本目标）
{task}

## 对话流程分析
{attempts_summary}

## 已尝试失败的工具和方法（solution_plan中必须排除）
{failed_tools_summary}

## 历史失败记录（同一任务的失败历史，solution_plan中也必须排除）
{historical_summary}

## 分析框架

### 第一步：还原对话流程（起因→经过→结果）

1. **用户原始需求是什么？** 具体要解决什么问题？
2. **三现两原方法：现场、现物、现象 + 原理、原则列出可能原因**
### 第二步：对可能原因进行验证
可能的原因1: ...
解决方案: ...
验证方法: ...

可能的原因2: ...
解决方案: ...
验证方法: ...

## 输出格式
```json
{{
  "type": "analysis",
  "diagnosis": "完整的对话流程分析，包括：起因(用户需求)、经过(LLM理解→工具选择→工具执行→结果处理)、结果(最终输出与用户需求的差距)",
  "root_causes": ["根本原因1", "根本原因2", ...],
  "gap_analysis": "用户需求与最终输出之间的差距",
  "solution_plan": ["具体解决步骤1", "具体解决步骤2", ...],
  "confidence": 0.0-1.0
}}
```

## 规则
- 始终从用户需求出发，不要脱离用户原始问题
- 追溯完整的对话流程，而不是只看表面错误
- **重要：solution_plan中不能包含已失败的工具或方法（见上面两个列表）**
- 如无工具和方法可选，利用本地创造新的skills

"""

    def __init__(self, llm_client=None):
        self.llm_client = llm_client

    def analyze(self, failure_context: FailureContext) -> AnalysisResult:
        """Run ReAct analysis on the failure context

        Args:
            failure_context: Information about the failures

        Returns:
            AnalysisResult with diagnosis, environment, capabilities, and plan
        """
        _debug(f"Starting ReAct analysis for task: {failure_context.task[:50]}...")

        # Build attempts summary
        attempts_summary = []
        failed_tools = set()
        for i, attempt in enumerate(failure_context.attempts, 1):
            tool_name = attempt.get('tool', 'unknown')
            failed_tools.add(tool_name)
            attempts_summary.append(f"""
Attempt {i}:
- Tool: {tool_name}
- Result: {attempt.get('result', 'no result')[:200]}
- Error: {attempt.get('error', 'none')}
- Advice: {attempt.get('judge_advice', 'none')}
""")
            # Log failed attempt to file
            self._log_failed_attempt(failure_context.task, tool_name, attempt)

        attempts_text = "\n".join(attempts_summary)

        # Build failed tools summary for prompt
        failed_tools_summary = "\n".join([f"- {t}" for t in failed_tools]) if failed_tools else "无"

        # Get historical failures for the same task
        historical = self._get_historical_failures(failure_context.task)
        historical_summary = ""
        if historical:
            for task, entries in historical.items():
                tools_in_history = list(set([e["tool"] for e in entries]))
                historical_summary += f"\n任务'{task}'历史失败工具: {', '.join(tools_in_history)}"
        if not historical_summary:
            historical_summary = "\n历史记录中无当前任务失败记录"

        # Get environment info
        environment = self._gather_environment()

        # Get available capabilities
        capabilities = self._get_capabilities()

        # Build prompt
        prompt = self.ANALYSIS_PROMPT.format(
            task=failure_context.task,
            attempts_summary=attempts_text,
            failed_tools_summary=failed_tools_summary,
            historical_summary=historical_summary
        )

        # Use LLM for analysis
        result_text = self._call_llm(prompt)

        # Parse result
        result = self._parse_analysis_result(
            result_text,
            failure_context,
            environment,
            capabilities
        )
        _debug(f"[analyze] completed: confidence={result.confidence}, diagnosis={result.diagnosis[:60]}")
        return result

    def _gather_environment(self) -> Dict[str, Any]:
        """Gather current environment information"""
        import platform
        return {
            "cwd": os.getcwd(),
            "platform": platform.platform(),
            "python_version": platform.python_version(),
            "env_vars": {
                "MODEL": os.getenv("MODEL_ID", "unknown"),
                "HAS_ANTHROPIC_KEY": bool(os.getenv("ANTHROPIC_AUTH_TOKEN")),
                "HAS_MINIMAX_KEY": bool(os.getenv("MINIMAX_API_KEY")),
            }
        }

    def _log_failed_attempt(self, task: str, tool_name: str, attempt: Dict[str, Any]) -> None:
        """Log failed attempt to file for tracking"""
        import json
        from datetime import datetime
        log_file = os.path.join(os.path.dirname(__file__), "failed_attempts.jsonl")

        log_entry = {
            "timestamp": datetime.now().isoformat(),
            "task": task,
            "tool": tool_name,
            "result": attempt.get('result', '')[:500],
            "error": attempt.get('error', ''),
            "judge_advice": attempt.get('judge_advice', ''),
        }

        try:
            with open(log_file, "a", encoding="utf-8") as f:
                f.write(json.dumps(log_entry, ensure_ascii=False) + "\n")
            _debug(f"[_log_failed_attempt] logged: tool={tool_name}")
        except Exception as e:
            _debug(f"[_log_failed_attempt] failed to log: {e}")

    def _get_historical_failures(self, current_task: str = None) -> Dict[str, List[Dict]]:
        """Read historical failures from log file, optionally filtered by task similarity"""
        import json
        log_file = os.path.join(os.path.dirname(__file__), "failed_attempts.jsonl")
        historical = {}

        try:
            if not os.path.exists(log_file):
                return historical

            with open(log_file, "r", encoding="utf-8") as f:
                for line in f:
                    try:
                        entry = json.loads(line.strip())
                        task = entry.get("task", "unknown")

                        # If current_task provided, only include exact matches or similar tasks
                        if current_task:
                            # Skip if task doesn't match current_task
                            if task != current_task:
                                continue

                        if task not in historical:
                            historical[task] = []
                        historical[task].append({
                            "tool": entry.get("tool", ""),
                            "timestamp": entry.get("timestamp", ""),
                            "judge_advice": entry.get("judge_advice", ""),
                        })
                    except json.JSONDecodeError:
                        continue

            _debug(f"[_get_historical_failures] loaded {len(historical)} tasks from history")
        except Exception as e:
            _debug(f"[_get_historical_failures] failed to read: {e}")

        return historical

    def _get_capabilities(self) -> List[str]:
        """Get available capabilities/tools"""
        capabilities = [
            "bash - Execute shell commands",
            "read_file - Read file contents",
            "write_file - Write/create files",
            "edit_file - Edit existing files",
            "web_search - Search the internet (returns URLs)",
            "web_fetch - Fetch and parse web pages",
            "glob - Find files by pattern",
            "grep - Search file contents",
            "task_create/task_list - Manage tasks",
            "TodoWrite - Update todo list",
            "background_run - Run commands in background",
        ]
        return capabilities

    def _call_llm(self, prompt: str) -> str:
        """Call LLM for analysis"""
        try:
            auth_token = os.getenv("ANTHROPIC_AUTH_TOKEN", "")
            base_url = os.getenv("ANTHROPIC_BASE_URL") or "https://api.minimaxi.com/anthropic/"

            import anthropic
            client = anthropic.Anthropic(api_key=auth_token, base_url=base_url)

            response = client.messages.create(
                model="MiniMax-M2.7",
                max_tokens=8000,
                system="You are a failure analysis expert. Analyze the situation and provide structured JSON output.",
                messages=[{"role": "user", "content": prompt}]
            )

            result = response.content[0].text if response.content else ""
            _debug(f"[LLM raw response]\n{result[:500]}...")
            return result

        except Exception as e:
            _debug(f"LLM analysis failed: {e}")
            return ""

    def _parse_analysis_result(
        self,
        result_text: str,
        failure_context: FailureContext,
        environment: Dict[str, Any],
        capabilities: List[str]
    ) -> AnalysisResult:
        """Parse the analysis result from LLM or fallback"""
        import json
        import re

        # Try to extract JSON from the result
        try:
            # Find JSON in the text (expanded to include new fields)
            json_match = re.search(r'\{[^{}]*"diagnosis"[^{}]*\}', result_text, re.DOTALL)
            if json_match:
                data = json.loads(json_match.group(0))
                result = AnalysisResult(
                    diagnosis=data.get("diagnosis", "Unknown diagnosis"),
                    environment=data.get("environment", environment),
                    capabilities=data.get("capabilities", capabilities),
                    solution_plan=data.get("solution_plan", data.get("plan", [])),
                    confidence=data.get("confidence", 0.5),
                    reasoning_trace=[{"raw": result_text[:500]}],
                    root_causes=data.get("root_causes", []),
                    gap_analysis=data.get("gap_analysis", "")
                )
                _debug(f"[Parsed AnalysisResult] diagnosis={result.diagnosis[:80]}, confidence={result.confidence}, plan_steps={len(result.solution_plan)}, root_causes={len(result.root_causes)}")
                return result
        except (json.JSONDecodeError, KeyError) as e:
            _debug(f"Failed to parse analysis JSON: {e}")

        # Fallback: use the failure context info
        result = AnalysisResult(
            diagnosis=f"Previous tool '{failure_context.last_tool}' failed to produce satisfactory results.",
            environment=environment,
            capabilities=capabilities,
            solution_plan=[
                "Review the judge advice and try a different approach",
                "Break down the problem into smaller steps",
                "Consider using alternative tools"
            ],
            root_causes=[f"Tool '{failure_context.last_tool}' returned unsatisfactory results"],
            gap_analysis="Output does not fully satisfy user needs",
            confidence=0.3,
            reasoning_trace=[{"fallback": True}]
        )
        _debug(f"[Fallback AnalysisResult] diagnosis={result.diagnosis[:80]}, confidence={result.confidence}")
        return result


async def run_react_analysis(
    task: str,
    failure_context: FailureContext,
    llm_client=None
) -> AnalysisResult:
    """Async wrapper for ReAct analysis

    Args:
        task: Original user task
        failure_context: Context about failures
        llm_client: Optional LLM client

    Returns:
        AnalysisResult with diagnosis and plan
    """
    _debug(f"[run_react_analysis] task={task[:50]}..., last_tool={failure_context.last_tool}")
    analyzer = ReActAnalyzer(llm_client)
    result = analyzer.analyze(failure_context)
    _debug(f"[run_react_analysis] returned AnalysisResult confidence={result.confidence}, diagnosis={result.diagnosis[:60]}")
    return result


def format_recovery_message(analysis: AnalysisResult) -> str:
    """Format analysis result as a message for the agent

    Args:
        analysis: AnalysisResult from ReAct

    Returns:
        Formatted message string
    """
    lines = [
        "## 失败分析与解决计划",
        "",
        "### 对话流程诊断",
        analysis.diagnosis,
        "",
    ]

    # Add root causes if available
    if analysis.root_causes:
        lines.extend([
            "### 根本原因分析",
        ])
        for i, cause in enumerate(analysis.root_causes, 1):
            lines.append(f"{i}. {cause}")
        lines.append("")

    # Add gap analysis if available
    if analysis.gap_analysis:
        lines.extend([
            "### 用户需求差距分析",
            analysis.gap_analysis,
            "",
        ])

    lines.extend([
        "### 当前环境",
        f"- 工作目录: {analysis.environment.get('cwd', 'unknown')}",
        f"- 平台: {analysis.environment.get('platform', 'unknown')}",
        "",
        "### 可用能力",
    ])

    for cap in analysis.capabilities[:5]:  # Limit to top 5
        lines.append(f"- {cap}")

    lines.extend([
        "",
        "### 解决计划",
    ])

    if analysis.solution_plan:
        _debug(f"[format_recovery_message] solution_plan ({len(analysis.solution_plan)} steps): {analysis.solution_plan}")
        for i, step in enumerate(analysis.solution_plan, 1):
            lines.append(f"{i}. {step}")
    else:
        lines.append("暂无详细计划，请尝试其他方法")

    lines.extend([
        "",
        f"置信度: {analysis.confidence:.0%}",
        "",
        "请根据以上分析制定具体行动。"
    ])

    result = "\n".join(lines)
    _debug(f"[format_recovery_message]\n{result[:300]}...")
    return result